### PR TITLE
Add healthcheck command in wirecloud's image

### PR DESCRIPTION
**Pull request by samgh96**
This PR adds a healthcheck command in the Dockerfile.

### CODE REVIEW

**Comment by aarranz** [comment]
Hi @samgh96,

thanks for the contribution!

Only some details, I think the default timeout is too large (30s), taking into account that the version request should take ~20 ms in a decent machine. It's true that default should cope with small installations and use a timeout with enough room for taking into account some lags. I think that something in the range of 3s would be a better option.

Also, it'd be great if you add this healthcheck configuration on the other images.

**Comment by aarranz** [comment]
Can you add the healthcheck also on the `dev` image? Also, is it really needed the ` || exit 1` part of the healthcheck command?

**Comment by samgh96** [comment]
It is, HEALTHCHECK only supports exit codes of 0 and 1, and `curl --fail` exit code differ from 1 depending on the error.

**Comment by aarranz** [comment]
Ok, thanks 😄. So the only missing piece is to add the healthcheck on the dev image and I will merge your PR.

**Pull request merged**
